package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"errors"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// IngestMalaysiaPDPAScannerFinding is the resolver for the ingestMalaysiaPDPAScannerFinding field.
func (r *mutationResolver) IngestMalaysiaPDPAScannerFinding(ctx context.Context, input types.IngestMalaysiaPDPAScannerFindingInput) (*types.IngestMalaysiaPDPAScannerFindingPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionMalaysiaPDPAScannerFindingIngest)
	if err != nil {
		return nil, err
	}

	result, err := r.probo.MalaysiaPDPAScannerFindings.Ingest(
		ctx,
		scope,
		&probo.IngestMalaysiaPDPAScannerFindingRequest{
			OrganizationID: input.OrganizationID,
			ExternalID:     input.ExternalID,
			Source:         input.Source,
			CheckKey:       input.CheckKey,
			Severity:       input.Severity,
			Summary:        input.Summary,
			Evidence:       json.RawMessage(input.Evidence),
			ObservedAt:     input.ObservedAt,
			RuleVersion:    input.RuleVersion,
			RuleSource:     input.RuleSource,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot ingest Malaysia PDPA scanner finding", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	scannerFinding := types.NewMalaysiaPDPAScannerFinding(
		result.ScannerFinding,
		result.Finding,
		result.Evidence,
	)

	return &types.IngestMalaysiaPDPAScannerFindingPayload{
		ScannerFinding: scannerFinding,
		Finding:        scannerFinding.Finding,
		Created:        result.Created,
	}, nil
}
